# Generated by Django 5.0.7 on 2024-08-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(choices=[('bedcott', 'bedcott'), ('sofa-set', 'sofa-set'), ('chairs', 'chair'), ('dhiwan', 'dhiwan'), ('pooja stand', 'pooja stand'), ('alamara', 'alamara')], max_length=150)),
                ('BrandName', models.CharField(max_length=50)),
                ('RetailPrice', models.CharField(max_length=20)),
                ('SalePrice', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
